### PR TITLE
Feature: Active image for completed progress

### PR DESCRIPTION
**Pull request by g00m**
I added images for complete steps. Its working if you set custom image or keep the default numbers.

ps: I tried not to break your linter this time :D

### CODE REVIEW

**Comment by jayahariv** [comment]
Hi, 
I am really sorry to close the pull request. I was confused by my own pull request. I just reopened it.

**Comment by g00m** [comment]
Np. Im currently try to resolve the issues in the example but having trouble with the storyboard part :D 

edit: I will work on it tomorrow, except you will fix it till then ;)

**Comment by jayahariv** [comment]
I edited the storyboard, by adding separate view controllers.

Whats the issues in the example? can you list them? We can fix it one by one if that helps you.

**Comment by g00m** [comment]
wait a sec till you merge. I will make some changes that the checkmark uses the correct active color from the new array :)

**Comment by g00m** [comment]
Now the conflicts are resolved and you could merge it ;)

**Review by jayahariv — APPROVED** [review]
Suggestion: instead of users setting the check images, we should provide a single property to set. That way we should draw it by ourselves.
Basically, the checkmark image is with us, and user setting the check mark code will be a repeating task. 

Example, 

// this should enable the check mark drawn.
progressBar.activeCheckMark = true

**Comment by jayahariv** [comment]
Current custom image option is awesome. And if set a single property we should provide a default image like 'check.png'.

**Comment by g00m** [comment]
I totally agree. I think we could use the icon I chose in the example (https://iconmonstr.com/check-mark-12-svg/). Will your write an "issue" for that? Maybe I am able to build that during this week

edit: we also need a "checkEverything()" method

**Comment by jkmathew** [comment]
@g00m  I'm sorry, 
What you meant by "checkEverything()"

**Comment by g00m** [comment]
That you can check everything so you can show the user that you completed a process

**Comment by g00m** [comment]
Btw are you updating the Cocoapod?! :)

**Pull request merged**
